### PR TITLE
Vet Clinic Database: Database Performance Audit

### PR DESCRIPTION
**Pull request by jugosack**
In this PR, we (@jugosack  and @joshualyngdoh) decreased the execution time of queries.

**Changes**
Decreased the execution time of the following queries:

**SELECT COUNT(*) FROM visits where animal_id = 4;**
<details>
<summary>Before</summary>
Before_4
</details>
<details>
<summary>After</summary>
After_4
</details>

**SELECT * FROM visits where vet_id = 2;**
<details>
<summary>Before</summary>
Before_2
</details>
<details>
<summary>After</summary>
After_2
</details>

 **SELECT * FROM owners where email = 'owner_18327@mail.com';**
<details>
<summary>Before</summary>
Before_3
</details>
<details>
<summary>After</summary>
After_3
</details>

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @jugosack , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
Great schema implementation ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] The execution time in the screenshots BEFORE is not significantly lower than 1 sec (1000ms) and I suggest running the populate database query a few times more as described in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=4%20Depening%20on,bigger%20than%201000ms.). 👍🏾 😄
- [ ] You have submitted a project, that doesn't show code contribution from your coding partner as this is a paired coding activity Kindly work together with your partner 🙏 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jugosack** [comment]
HI @alexander16108 

Please find new metrics regarding database performance improvement by following:
**SELECT COUNT(*) FROM visits where animal_id = 4;**
<details>
<summary>Before</summary>
Before_4
</details>
<details>
<summary>After</summary>
After_4
</details>

**Comment by alexander16108** [comment]
@jugosack  your coding partners should make contributions on this pr in other to move forward as I suggested before your execution time on `before` should be less than or equal to 1000ms and currently its over 1000ms run the query a few times to improve the execution time 👍🏾 wish you best of luck

**Review by 1GORDON — COMMENTED** [review]
# Status: INVALID

Hi @jugosack & @joshualyngdoh 👏

- Hello, you have done well reaching this point of the milestone. But there are some issues that you still need to work on to go to the next project but you are almost there!
### This project will be marked as invalid and it won't affect the number of your weekly reviews.

- [x] Kindly remove the entire live demo section from your readme file since this project is not deployed. This is a general requirement for all projects.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by omarsalem7 — APPROVED** [review]
Hi @jugosack , @joshualyngdoh 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
